name: Code Style Check

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install JavaScript dependencies
        run: |
          cd frontend
          npm install
          npm install -g eslint eslint-config-next @babel/core @babel/eslint-parser

      - name: Run ESLint on JavaScript files
        run: |
          cd frontend
          npx eslint .
